### ISSUE TITLE
BattleMatrix out of memory when running large Pokemon pool

### ISSUE THREAD

**Issue by biowpn** [biowpn/GoBattleSim#13]
example input

```
name,fmove,cmove,cmove2,cp
"fire,water,grass","*","*","*current",1500
```

the error produced by Chrome:

```
GBS_Engine.js:1 Uncaught RuntimeError: memory access out of bounds
    at wasm-function[691]:0x16d4f
    at Module._GBS_prepare (http://127.0.0.1/src/GBS_Engine.js:1:84488)
    at ccall (http://127.0.0.1/src/GBS_Engine.js:1:6773)
    at http://127.0.0.1/src/GBS_Engine.js:1:7123
    at Object.GBS.prepare (http://127.0.0.1/src/GBS_Simulator_Interface.js:48:2)
    at http://127.0.0.1/src/GBS_BattleMatrix.js:306:13
```

**Comment by biowpn** [comment]
a partial fix in 0afc2cf7686d4456b5c27fff82977d40e73210fd

There are still problems with GBS.collect(), related to this issue with emcripten:

https://github.com/emscripten-core/emsdk/issues/380

https://github.com/emscripten-core/emscripten/issues/9013

For now, just ask the user for confirmation before running large matrices.
